SELECT diDate AS Datum, COUNT(*) AS Anzahl,
CONCAT (
	LEFT( CAST(SUM(CAST(diVk AS BIGINT)) AS VARCHAR(50)), LEN(CAST(SUM(CAST(diVk AS BIGINT)) AS VARCHAR(50))) - 2 ),
	',',
	RIGHT(CAST(SUM(CAST(diVk AS BIGINT)) AS VARCHAR(50)), 2)
) AS Verkaufspreis
FROM RW_APOBASE_Rezept
WHERE ERezeptID IS NULL
  AND diDate BETWEEN 20210100 AND 20241200
GROUP BY diDate
ORDER BY diDate ASC;

SELECT diDate AS Datum, COUNT(*) AS Anzahl,
CONCAT (
	LEFT( CAST(SUM(CAST(diVk AS BIGINT)) AS VARCHAR(50)), LEN(CAST(SUM(CAST(diVk AS BIGINT)) AS VARCHAR(50))) - 2 ),
	',',
	RIGHT(CAST(SUM(CAST(diVk AS BIGINT)) AS VARCHAR(50)), 2)
) AS Verkaufspreis
FROM RW_APOBASE_Rezept
WHERE ERezeptID IS NOT NULL
  AND diDate BETWEEN 20210100 AND 20241200
GROUP BY diDate
ORDER BY diDate ASC;