---------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------
-- /* Reset Fehler */   	SELECT DISTINCT(ERezeptID) INTO #ERezeptList FROM RW_APOBASE_Rezept WHERE cKontrollStatus=4 AND ERezeptID IS NOT NULL AND iRpNr > 0 AND bStorno = 0;DELETE RW_EREZEPT_Abrechnung WHERE ERezeptID IN (SELECT ERezeptID FROM #ERezeptList);DELETE RW_EREZEPT_RZErgebnis WHERE ERezeptID IN (SELECT ERezeptID FROM #ERezeptList);UPDATE RW_APOBASE_Rezept SET cKontrollStatus = 0, cFehlerTyp = 0 WHERE ERezeptID IN (SELECT ERezeptID FROM #ERezeptList);DROP TABLE #ERezeptList;
/* Aktualisierung */ 		DELETE RW_EREZEPT_RZErgebnis where ERezeptID in (select ERezeptID from RW_APOBASE_Rezept where cKontrollStatus IN (0,2) or iRpNr = 0 or bstorno = 1);return;
---------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------
/* Fehler-Meldungen */ 		SELECT DISTINCT(REPLACE(ERezeptID, '.', ''))as ID,left(convert(nvarchar(1), status),1) as S,dbo.fn_Format_Notification(Kommentar) AS Message, Kommentar from RW_EREZEPT_RZErgebnis order by s,Kommentar;return;
/* Fehler-Anzahl */			SELECT COUNT(DISTINCT(ERezeptID)) as c, dbo.fn_Format_Notification(Kommentar) AS Message from RW_EREZEPT_RZErgebnis group by Kommentar order by c desc
/* Preis */					SELECT DISTINCT(REPLACE(r.ERezeptID, '.', ''))as ID,r.didate,r.cKontrollStatus as ks,r.iAnzahl as Anzahl,r.strText AS Medi,r.diVk AS VK,r.Markt as M,r.Rabattvertragerfuellung as R,r.PreisguenstigesFAM as P,r.ImportFAM as I, dbo.fn_Format_Notification(e.Kommentar) AS Message from RW_APOBASE_Rezept r inner join RW_EREZEPT_RZErgebnis e on r.ERezeptID = e.ERezeptID where r.ERezeptID is not null and r.bStorno = 0 and r.cKontrollStatus in (3,4) order by r.divk desc
/* Datum */					SELECT DISTINCT(REPLACE(r.ERezeptID, '.', ''))as ID,r.didate,r.cKontrollStatus as ks,r.iAnzahl as Anzahl,r.strText AS Medi,r.diVk AS VK,r.Markt as M,r.Rabattvertragerfuellung as R,r.PreisguenstigesFAM as P,r.ImportFAM as I, dbo.fn_Format_Notification(e.Kommentar) AS Message from RW_APOBASE_Rezept r inner join RW_EREZEPT_RZErgebnis e on r.ERezeptID = e.ERezeptID where r.ERezeptID is not null and r.bStorno = 0 and r.cKontrollStatus in (3,4) order by r.didate asc
/* Hochladbar */			SELECT COUNT(DISTINCT(ERezeptID)) AS Uploadable FROM RW_APOBASE_Rezept WHERE ERezeptID IS NOT NULL AND cKontrollStatus = 0 AND bStorno = 0 AND iRpNr > 0;SELECT DISTINCT ERezeptId,* FROM RW_APOBASE_Rezept WHERE ERezeptID is not null and cKontrollStatus = 0 and cFehlerTyp = 0 and bStorno = 0 and iRpNr > 0 AND convert(date, convert(varchar(8), didate)) < dateadd(day, -7, cast(GETDATE() as date)) ORDER BY diDate DESC;
--------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------
/* Kundenliste */ 	   	 	DECLARE @f nvarchar(max) = 'Fehlermeldung';																																																																															use apobase;SELECT Distinct(REPLACE(ERezeptID, '.', ''))as ID,SUBSTRING(CONVERT(VARCHAR(10), didate), 7, 2) + '/' + SUBSTRING(CONVERT(VARCHAR(10), didate), 5, 2) + '/' + left(CONVERT(VARCHAR(10), didate), 4) AS Datum,CASE WHEN LEN(CONVERT(VARCHAR(20), ditime)) = 8 THEN '0' + LEFT(CONVERT(VARCHAR(20), ditime), 1) + ':' + SUBSTRING(RIGHT(CONVERT(VARCHAR(20), ditime), 7), 1, 2)ELSE LEFT(CONVERT(VARCHAR(20), ditime), LEN(CONVERT(VARCHAR(20), ditime)) - 7) + ':' + SUBSTRING(RIGHT(CONVERT(VARCHAR(20), ditime), 7), 1, 2)END AS Uhrzeit, strtext, didate FROM RW_APOBASE_Rezept WHERE ERezeptID IN (SELECT ERezeptID FROM RW_EREZEPT_RZErgebnis WHERE not dipzn in ('6461110', '2567024') and Kommentar LIKE '%' + @f + '%') order by didate
/* Dokumentation */ 		SELECT Distinct(REPLACE(ERezeptID, '.', ''))as ID,SUBSTRING(CONVERT(VARCHAR(10), didate), 7, 2) + '/' + SUBSTRING(CONVERT(VARCHAR(10), didate), 5, 2) + '/' + left(CONVERT(VARCHAR(10), didate), 4) AS Datum,CASE WHEN LEN(CONVERT(VARCHAR(20), ditime)) = 8 THEN '0' + LEFT(CONVERT(VARCHAR(20), ditime), 1) + ':' + SUBSTRING(RIGHT(CONVERT(VARCHAR(20), ditime), 7), 1, 2)ELSE LEFT(CONVERT(VARCHAR(20), ditime), LEN(CONVERT(VARCHAR(20), ditime)) - 7) + ':' + SUBSTRING(RIGHT(CONVERT(VARCHAR(20), ditime), 7), 1, 2)END AS Uhrzeit, strtext, didate FROM RW_APOBASE_Rezept WHERE not dipzn in ('6461110', '2567024') and ERezeptID in (Select ERezeptID from RW_APOBASE_Rezept where ERezeptID is not null and (iAnzahl > 500 or Rabattvertragerfuellung > 2 or PreisguenstigesFAM > 2 or ImportFAM > 2)) and ERezeptID IN (SELECT ERezeptID FROM RW_EREZEPT_RZErgebnis WHERE Kommentar LIKE '%fhir%') order by didate
---------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------
/* Massen-Update */			DECLARE @i nvarchar(max) = 'Fehlermeldung';																																																																																																																		use apobase;SELECT Distinct(REPLACE(ERezeptID, '.', ''))as ID,iAnzahl as Anzahl,didate as date,cKontrollStatus as KS,diPzn as PZN,strText,diVk AS VK,diFbtrg as Fest, diZahlbetrag as ZB, iAnteil as Anteil, diZuzahlung as ZZZ,Markt as M,Rabattvertragerfuellung as R,PreisguenstigesFAM as P,ImportFAM as I, Begruendung FROM RW_APOBASE_Rezept WHERE ERezeptID IN (SELECT ERezeptID FROM RW_EREZEPT_RZErgebnis  WHERE not dipzn in ('6461110', '2567024') and Kommentar LIKE '%' + @i + '%') order by didate
							RETURN

							UPDATE RW_APOBASE_Rezept set cKontrollStatus = 0, cFehlerTyp = 0 where ERezeptID in (SELECT ERezeptID FROM RW_EREZEPT_RZErgebnis  WHERE Kommentar LIKE '%' + @i + '%') 
							DELETE RW_EREZEPT_Abrechnung where ERezeptID in (SELECT ERezeptID FROM RW_EREZEPT_RZErgebnis  WHERE Kommentar LIKE '%' + @i + '%')
							DELETE RW_EREZEPT_RZErgebnis where ERezeptID in (SELECT ERezeptID FROM RW_EREZEPT_RZErgebnis  WHERE Kommentar LIKE '%' + @i + '%')
---------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------
