DECLARE @ERezeptID NVARCHAR(MAX) = '0000000000';																																																																																									DECLARE @ERezeptLength INT = LEN(@ERezeptID) IF (@ERezeptLength = 17) SET @ERezeptID = SUBSTRING(CONVERT(NVARCHAR(25), @ERezeptID), 0, 4) + '.' + SUBSTRING(CONVERT(NVARCHAR(25), @ERezeptID), 4, 3) + '.' + SUBSTRING(CONVERT(NVARCHAR(25), @ERezeptID), 7,3)+'.'+SUBSTRING(CONVERT(nvarchar(25), @ERezeptID),10,3)+'.'+ SUBSTRING(CONVERT(nvarchar(25), @ERezeptID),13,3)+'.'+SUBSTRING(CONVERT(nvarchar(25), @ERezeptID),16,2); ELSE IF (@ERezeptLength < 17) BEGIN IF ((SELECT COUNT(DISTINCT ERezeptID) FROM RW_APOBASE_Rezept WHERE ERezeptID LIKE '%' + @ERezeptID) = 1) BEGIN SET @ERezeptID = (SELECT DISTINCT ERezeptID FROM RW_APOBASE_Rezept WHERE ERezeptID LIKE '%' + @ERezeptID) END ELSE BEGIN SELECT ERezeptID, diDate, strText FROM RW_APOBASE_Rezept WHERE ERezeptID LIKE '%' + @ERezeptID RETURN END END DECLARE @D INT = (SELECT TOP 1 didate FROM RW_APOBASE_Rezept WHERE ERezeptID = @ERezeptID);DECLARE @R INT = (SELECT TOP 1 irpnr FROM RW_APOBASE_Rezept WHERE ERezeptID = @ERezeptID);DECLARE @P INT = (SELECT TOP 1 dipzn FROM RW_APOBASE_Rezept WHERE ERezeptID = @ERezeptID and dipzn not IN ('6461110', '2567024'));DECLARE @L INT = (SELECT TOP 1 dilfdnr FROM RW_APOBASE_Vorgaenge WHERE iRpNr = @R and diPzn = @P and didate = @D);DECLARE @V INT = (SELECT TOP 1 ivgnr FROM rw_apobase_vorgaenge WHERE diLfdNr = @L);DECLARE @S nvarchar(50) = (SELECT TOP 1 SecurpharmID FROM RW_MODUL_SEC_VORGANG_SECURPHARM WHERE ivgnr = @V AND didate = @D AND dipzn = @P); 		DECLARE @Attribute SMALLINT = 1100;DECLARE @iAnteil INT = 0, @diZuzahlung INT = 0;DECLARE @Anzahl INT = 1;DECLARE @Charge NVARCHAR(25) = '0000000';DECLARE @Hämo INT = '000000';DECLARE @Ks TINYINT = 2, @Ft TINYINT = 5;DECLARE @Storno INT = 0; DECLARE @ART INT; DECLARE @Reason NVARCHAR(MAX);

-- /* Profil */			update RW_EREZEPT_Abrechnung set Blob = REPLACE(CAST(Blob as nvarchar(max)), '|1.5', '|1.4') WHERE ERezeptID = @ERezeptID; UPDATE RW_APOBASE_Rezept set cKontrollStatus = 0, cFehlerTyp = 0 where ERezeptID = @ERezeptID; delete RW_EREZEPT_RZErgebnis where ERezeptID = @ERezeptID;
-- /* RESET  */         EXEC sp_reset_rx @ID = @ERezeptID;
-- /* FLAG   */         SET @Attribute = 1100;																																																														EXEC sp_reset_rx @ID = @ERezeptID; DECLARE @Markt INT = SUBSTRING(CAST(@Attribute AS CHAR),1,1),@Rabattvertragerfuellung INT = SUBSTRING(CAST(@Attribute AS CHAR),2,1), @PreisguenstigesFAM int = SUBSTRING(CAST(@Attribute AS CHAR),3,1), @ImportFAM int = SUBSTRING(CAST(@Attribute AS CHAR),4,1); UPDATE RW_APOBASE_Rezept SET markt = @Markt, Rabattvertragerfuellung = @Rabattvertragerfuellung, PreisguenstigesFAM = @PreisguenstigesFAM, ImportFAM = @ImportFAM WHERE ERezeptID = @ERezeptID;
-- /* COST   */         SET @iAnteil = 500; SET @diZuzahlung = 0;																																																									EXEC sp_reset_rx @ID = @ERezeptID; UPDATE RW_APOBASE_Rezept SET diZahlbetrag=(@iAnteil+@diZuzahlung)/iAnzahl, iAnteil=@iAnteil/iAnzahl, diZuzahlung=@diZuzahlung/iAnzahl WHERE ERezeptID = @ERezeptID and diPzn = @P; UPDATE V SET v.diZahlbetrag = r.diZahlbetrag, v.iAnteil=r.iAnteil, v.diZuzahlung=r.diZuzahlung FROM RW_APOBASE_Vorgaenge v INNER JOIN RW_APOBASE_Rezept r on r.iRpNr = V.iRpNr and r.didate = v.didate WHERE v.diLfdNr = @L;
-- /* SEL    */         EXEC sp_reset_rx @ID = @ERezeptID;																																																											UPDATE RW_APOBASE_Rezept SET cRpStatus = 5, iRpNr = 0 WHERE ERezeptID = @ERezeptID;
-- /* COUNT  */         SET @Anzahl = 1;																																																															UPDATE RW_APOBASE_Rezept SET iAnzahl = @Anzahl WHERE ERezeptID = @ERezeptID AND diPzn = @P; UPDATE RW_APOBASE_Vorgaenge SET iAnzahl = @Anzahl WHERE diLfdNr = @L; 
-- /* CANCEL */         SET @Storno = 0;																																																															UPDATE RW_APOBASE_Rezept SET bStorno = @Storno WHERE ERezeptID = @ERezeptID; UPDATE RW_APOBASE_Vorgaenge SET bStorno = @Storno WHERE diDate = @d AND iRpNr = @R;
-- /* BILLED */         SET @KS = 2; SET @Ft = 5; 																																																													UPDATE RW_APOBASE_Rezept set cKontrollStatus = @KS, cFehlerTyp = @Ft where ERezeptID = @ERezeptID; DELETE FROM RW_EREZEPT_RZErgebnis WHERE ERezeptID = @ERezeptID;
-- /* BATCH  */         SET @Charge = '0000000';																																																													EXEC sp_reset_rx @ID = @ERezeptID; DELETE RW_MODUL_SEC_Securpharm WHERE SecurPharmID = @S; DELETE RW_MODUL_SEC_VORGANG_SECURPHARM WHERE SecurPharmID = @S; INSERT INTO RW_MODUL_SEC_VORGANG_SECURPHARM (diLfdNr, SecurpharmID, iVgNr, diPzn, diDate) VALUES (@L, @ERezeptID, @V ,@P, @D); INSERT INTO RW_MODUL_SEC_Securpharm (SecurPharmID, Charge, SN, Verfall) VALUES (@ERezeptID, @Charge, 'Manuell', 99998877);
-- /* Art */			   SET @Art = 12;																																																																UPDATE RW_EREZEPT_Aenderungen SET Art = @Art WHERE ERezeptID = @ERezeptID
-- /* Reason */			SET @Reason = '';																																																															UPDATE RW_APOBASE_Rezept SET Begruendung = @Reason WHERE ERezeptID = @ERezeptID;
-- /* SPLIT  */         SET @Hämo = '000000';																																																														EXEC sp_reset_rx @ID = @ERezeptID; UPDATE RW_APOBASE_Rezept set iRpNr = 0, ERezeptID = null OUTPUT inserted.iRpNr, inserted.ERezeptID, inserted.strText WHERE didate = @D AND iRpNr = @R AND diLfdNr NOT IN (@Hämo) AND @R IN (SELECT iRpNr FROM RW_APOBASE_Rezept WHERE diLfdNr = @Hämo) AND @D IN (SELECT didate FROM RW_APOBASE_Rezept WHERE diLfdNr = @Hämo);
   /* QUERY  */																																																																						SELECT dilfdnr,iRpNr as RpNr,iAnzahl as Anzahl,diPzn as PZN, diKdIkNummer as IkNr, strKundenName AS kunde,strText,bstorno,diVk AS VK,diFbtrg as Fest, diZahlbetrag as ZB, iAnteil as Anteil, diZuzahlung as ZZZ,Markt as M,Rabattvertragerfuellung as R,PreisguenstigesFAM as P,ImportFAM as I, Begruendung FROM RW_APOBASE_Rezept WHERE ERezeptID = @ERezeptID; SELECT ERezeptID as ID,diDate, ditime, cKontrollStatus as KS,cFehlerTyp as FT,Verordnung,Abrechnung,Dispense,Quittung FROM ERezeptView WHERE ERezeptID = @ERezeptID;  SELECT diLfdNr,iVgNr as VgNr,iRpNr as RpNr,iAnzahl as Anzahl,diPzn,strText, didate, ditime, diVk AS VK,diFbtrg as Fest, diZahlbetrag as ZB, iAnteil as Anteil, diZuzahlung as ZZZ  FROM RW_APOBASE_Vorgaenge WHERE didate = @D and iRpNr = @R;  SELECT ERezeptID,Status,TRIM(Kommentar) AS msg, Trim(Kurztext) AS synopsis  FROM RW_EREZEPT_RZErgebnis WHERE ERezeptID = @ERezeptID; SELECT * FROM RW_MODUL_SEC_Securpharm WHERE SecurPharmID = @S; select generikum, Apo_Vk, Festbetrag from apo_abda_pac_apo where PZN = @P;select * from RW_EREZEPT_Aenderungen where ERezeptID = @ERezeptID;

