ALTER TABLE [MODUL_Botendienst] 
ALTER COLUMN strname NVARCHAR(70) NULL
ALTER TABLE [MODUL_Botendienst] 
ALTER COLUMN strkundenname NVARCHAR(82) NULL

ALTER TABLE [RW_APOBASE_BestellNotiz] 
ALTER COLUMN strnotiz NVARCHAR(82) NULL

ALTER TABLE [RW_APOBASE_Bestellung] 
ALTER COLUMN strname NVARCHAR(70) NULL

ALTER TABLE [RW_APOBASE_BTMKartei] 
ALTER COLUMN strkundenname NVARCHAR(82) NULL

ALTER TABLE [RW_APOBASE_FAMPruefung] 
ALTER COLUMN strname NVARCHAR(70) NULL

ALTER TABLE [RW_APOBASE_LagerArtikel] 
ALTER COLUMN strname NVARCHAR(70) NULL 
ALTER TABLE [RW_APOBASE_LagerArtikel] 
ALTER COLUMN strnoleername NVARCHAR(70) NULL
ALTER TABLE [RW_APOBASE_LagerArtikel] 
ALTER COLUMN strlangname NVARCHAR(70) NULL

ALTER TABLE [RW_APOBASE_Lieferung] 
ALTER COLUMN strname NVARCHAR(70) NULL 

ALTER TABLE [RW_APOBASE_Nachlieferung] 
ALTER COLUMN strtext NVARCHAR(70) NULL 
ALTER TABLE [RW_APOBASE_Nachlieferung] 
ALTER COLUMN strkundenname NVARCHAR(82) NULL 

ALTER TABLE [RW_APOBASE_NachlieferungInfo] 
ALTER COLUMN strname NVARCHAR(82) NULL 

ALTER TABLE [RW_APOBASE_NLPosLog] 
ALTER COLUMN strbez NVARCHAR(70) NULL 
ALTER TABLE [RW_APOBASE_NLPosLog] 
ALTER COLUMN strlgname NVARCHAR(70) NULL 
ALTER TABLE [RW_APOBASE_NLPosLog] 
ALTER COLUMN strkdname NVARCHAR(82) NULL 

ALTER TABLE [RW_APOBASE_PosLog] 
ALTER COLUMN strbez NVARCHAR(70) NULL 
ALTER TABLE [RW_APOBASE_PosLog] 
ALTER COLUMN strlgname NVARCHAR(70) NULL 
ALTER TABLE [RW_APOBASE_PosLog] 
ALTER COLUMN strkdname NVARCHAR(82) NULL 

ALTER TABLE [RW_APOBASE_Rezept] 
ALTER COLUMN strtext NVARCHAR(70) NULL 
ALTER TABLE [RW_APOBASE_Rezept] 
ALTER COLUMN strkundenname NVARCHAR(82) NULL 

ALTER TABLE [RW_APOBASE_Vorgaenge] 
ALTER COLUMN strtext NVARCHAR(70) NULL
ALTER TABLE [RW_APOBASE_Vorgaenge] 
ALTER COLUMN strkundenname NVARCHAR(82) NULL 